config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :tags
  # General configuration
  root(to: 'application#main')
  concern(:autocompletable) do
    get  :autocomplete, on: :collection
  end

  # Static pages
  namespace :page do
    %i[
      api about committee connect help initiative issues join
      news prize publications seqcode linkout status
      sandbox stats videos
    ].each { |i| get(i) }
  end
  get  'help' => 'page#help_index', as: :help_index
  get  'help/:topic' => 'page#help', as: :help

  # Users
  get  'sysusers(.:format)' => 'users#index', as: :users
  get  'sysusers/:username(.:format)' => 'users#show', as: :user
  post 'sysusers/:username(.:format)' => 'users#update'
  get  'dashboard' => 'users#dashboard', as: :dashboard
  get  'contributors' => 'users#contributor_request', as: :contributor_request
  post 'contributors' => 'users#contributor_apply', as: :contributor_apply
  post 'contributors/grant/:username' => 'users#contributor_grant', as: :contributor_grant
  post 'contributors/deny/:username' => 'users#contributor_deny', as: :contributor_deny
  get  'curators' => 'users#curator_request', as: :curator_request
  post 'curators' => 'users#curator_apply', as: :curator_apply
  post 'curators/grant/:username' => 'users#curator_grant', as: :curator_grant
  post 'curators/deny/:username' => 'users#curator_deny', as: :curator_deny
  devise_for(:users, controllers: { registrations: 'users/registrations' })

  # Alerts (Notifications)
  resources(
    :notifications, path: 'alerts',
    only: %i[index show update destroy]
  ) do
    collection do
      post :all_seen
      post :all_destroy
    end
    member do
      post :toggle_seen
    end
  end

  # Names
  # --> Index
  get  'type-genomes(.:format)' => 'names#type_genomes', as: :name_type_genomes
  # --> Standard resources
  resources(:names) do
    collection do
      # --> Index
      get  :submitted
      get  :endorsed
      get  :draft
      get  :user
      get  :observing
      get  :linkout
      # --> User utilities
      get  :autocomplete
      get  :etymology_sandbox
      get  :syllabify
      # --> Curator utilities
      get  :unranked
      get  :unknown_proposal
    end
    member do
      # --> Display name
      get  :network
      get  :linkout
      get  :wiki
      # --> Edit name
      get  :edit_description
      get  :edit_type
      get  :edit_etymology
      get  :autofill_etymology
      get  :edit_notes
      get  :edit_rank
      get  :edit_links
      get  :edit_redirect
      post :return
      post :validate
      post :endorse
      post :temporary_editable
      # --> Edit user relationship to name
      get  :observe
      get  :unobserve
      post :claim
      post :unclaim
      post :demote
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Edit name relationships
      get  :edit_parent
      post :new_correspondence
      post :proposed_in, path: '/proposed_in/:publication_id'
      get  :corrigendum_in
      post :corrigendum
      post :emended_in, path: '/emended_in/:publication_id'
      post :assigned_in, path: '/assigned_in/:publication_id'
      post :not_validly_proposed_in,
           path: '/not_validly_proposed_in/:publication_id'
    end
    resources :pseudonyms
  end

  # Taxonomic placements
  resources(:placements, only: %i[create edit update destroy]) do
    post :prefer, on: :member
  end
  get '/placements/new/:name_id', controller: :placements, action: :new, as: :new_placement

  # Genomes
  resources(:genomes) do
    member do
      post  :update_external
      post  :recalculate_miga
      patch :update_accession
      get   :sample_map
    end
  end

  # Strains
  resources(:strains, only: %i[index show]) do
    member do
      get  :strain_info
      get  :link_genome
      post :link_genome_commit
      post :unlink_genome
    end
  end

  # Checks
  post 'check/:name_id(.:format)' => 'checks#update', as: :check

  # Register lists
  # --> Standard resources
  resources(:registers, param: :accession) do
    collection do
      get  :map
    end
    member do
      # --> Display
      get  :table
      get  :list
      get  :cite
      get  :certificate_image
      get  :sample_map
      get  :tree
      get  :reviewer_token
      post :reviewer_token, action: :reviewer_token_create
      delete :reviewer_token, action: :reviewer_token_delete
      # --> Register edit
      post :submit
      get  :return
      post :return, action: :return_commit
      post :endorse
      get  :notify
      post :notify, action: :notify_commit
      get  :prenotify
      post :prenotify, action: :prenotify_commit
      post :validate
      get  :editorial_checks
      get  :publish
      post :publish, action: :publish_commit
      patch :internal_notes
      post :nomenclature_review
      post :genomics_review
      get  :merge
      post :merge, action: :merge_commit
      get  :coauthors
      post :coauthors, action: :coauthors_commit
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Special curation pages
      get  :curation_genomics
      post :snooze_curation
      post :recheck_pdf_files
      # --> Edit user relationship to register list
      get  :observe
      get  :unobserve
      # --> Edit register relationships
      post :new_correspondence
    end
  end

  # Authors
  resources(:authors, concerns: :autocompletable)

  # Journals
  resources(:journals, only: %i[index show], param: :journal)

  # Publications
  resources(:publications, concerns: :autocompletable) do
    resources(:contacts, only: %i[new create show index])
    member do
      get  :names
    end
  end
  get  'doi/:doi' => 'publications#show', as: :doi, doi: /.+/
  resources(:contacts, only: []) do
    collection do
      get  :user
    end
  end

  # Publication Names (n:m relationship)
  get  'publications/:id/link_name' => 'publication_names#link_name', as: :link_publication_name
  post 'publications/:id/link_name' => 'publication_names#link_name_commit', as: :link_publication_commit_name

  # Other resources
  resources(:subjects, concerns: :autocompletable)
  resources(:tutorials, :publication_names)
  resources(:correspondences, only: []) do
    collection do
      get  :template
    end
  end
  resources(:curations, only: %i[create update])

  # Reports
  get 'reports/genomes/:id', to: 'reports#genome', as: :reports_genome

  # General Application
  get  'link' => 'application#short_link'
  get  'link/:path(.:format)' => 'application#short_link'
  get  'set/list' => 'application#set_list', as: :set_list
  get  'search' => 'application#search', as: :search
end

app/models/name/citations.rb
module Name::Citations
  def pull_citations
    publications = []

    vars = [base_name]
    vars << corrigendum_from.gsub(/^Candidatus /) if corrigendum_from?

    if %w[species subspecies].include?(rank)
      return publications unless genus

      vars += vars.map { |i| i.gsub(/^(\S)\S+ /, '\1. ') }
      genus.pull_citations
      genus.publications.each do |publication|
        next if publications.include?(publication)
        next unless vars.any? { |q| publication.include_term?(q) }

        publications << publication
        yield(publication) if block_given?
      end
    else
      vars.each do |q|
        query = { query: q, sort: 'deposited', order: 'asc' }
        Publication.query_crossref(query) do |publication|
          unless publications.include?(publication)
            publications << publication
            yield(publication) if block_given?
          end
        end
      end
    end

    self.publications += publications - self.publications
    publications
  end
end

app/models/name/external_resources.rb
module Name::ExternalResources
  ##
  # By default, external requests are deferred to a later time (async).
  # If set to +true+, external requests are performed on demand
  attr_accessor :make_external_requests

  ##
  # The class of an asynchronous job for external resources, required by
  # the +HasExternalResources+ interface
  def external_resources_job
    NameExternalResourcesJob
  end

  ##
  # Execute a programmatic search of the current name in the external +service+
  def external_search(service)
    unless make_external_requests
      queue_for_external_resources
      return
    end

    uri = send("#{service}_search_uri")
    body = external_request(uri, '{}')

    if body.present?
      send("#{service}_json=", body)
      send("#{service}_at=", Time.now)
    end
  end

  ##
  # Retrieve the cached response in JSON for the external +service+
  def external_json(service)
    send("#{service}_json")
  end

  ##
  # Indicate when the +service+ was last successfully queried
  def external_at(service)
    send("#{service}_at")
  end

  ##
  # Parse the cached JSON response as a hash, retrieving it if missing and
  # renewing it if too old (over 2 months ago)
  def external_hash(service)
    @external_hash ||= {}
    @external_hash[service] ||= nil
    return @external_hash[service] unless @external_hash[service].nil?

    # If the cached JSON is missing or old, retrieve anew
    if !external_json(service) || external_at(service) < 2.months.ago
      external_search(service)
    end

    # Return parsed cached response or nil
    if external_json(service)
      update_column(:queued_external, nil) if queued_for_external_resources
      @external_hash[service] = JSON.parse(
        external_json(service), symbolize_names: true
      )
    else
      nil
    end
  end

  def itis_search_uri
    base = 'https://www.itis.gov/ITISWebService/jsonservice'
    "#{base}/searchByScientificNameExact?srchKey=#{base_name}"
  end

  def itis_hash
    external_hash(:itis)
  end

  def itis_homonyms
    return [] unless itis_hash

    base = 'https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&'
    names = itis_hash[:scientificNames].compact || []
    names.map do |i|
      "<a href=\"#{base}&search_value=#{i[:tsn]}\" target=_blank>" \
        "<i>#{i[:combinedName]}</i> #{i[:author]} (<i>#{i[:kingdom]}</i>)" \
        '</a>'
    end
  end

  def gbif_search_uri
    base = 'https://api.gbif.org/v1'
    "#{base}/species?name=#{base_name}"
  end

  def gbif_hash
    external_hash(:gbif)
  end

  def gbif_homonyms(prefix = false, all = false)
    return [] unless gbif_hash

    base = 'https://www.gbif.org/species'
    names = gbif_hash[:results] || []
    names.map do |i|
      next if !all && !i[:nomenclaturalStatus].include?('VALIDLY_PUBLISHED')

      kingdom = i[:kingdom] ? "(<i>#{i[:kingdom]}</i>)" : ''
      name = i[:authorship].present? ? i[:canonicalName] : i[:scientificName]
      name ||= i[:scientificName] || i[:canonicalName]

      "<a href=\"#{base}/#{i[:key]}\" target=_blank>" \
        "#{'GBIF: ' if prefix}<i>#{name}</i> #{i[:authorship]} #{kingdom}</a>"
    end.compact
  end

  def irmng_search_uri
    base = 'https://www.irmng.org/rest/AphiaRecordsByNames'
    "#{base}?scientificnames[]=#{base_name}&like=false"
  end

  def irmng_hash
    external_hash(:irmng)
  end

  def irmng_homonyms(prefix = false)
    return [] unless irmng_hash && !irmng_hash.empty?

    (irmng_hash.first || []).map do |i|
      "<a href=\"#{i[:url]}\" target=_blank>" \
        "#{'IRMNG: ' if prefix}" \
        "<i>#{i[:scientificname]}</i> #{i[:authority]} " \
        "(<i>#{i[:kingdom]}</i>)</a>"
    end
  end

  def col_search_uri
    base = 'https://api.catalogueoflife.org/name/matching'
    "#{base}?q=#{base_name}&verbose=true"
  end

  def col_hash
    external_hash(:col)
  end

  def col_homonyms
    return [] unless col_hash && col_hash[:type] == 'exact'

    (col_hash[:alternatives] || []).map do |i|
      "#{i[:labelHtml]} " \
        '(<a href="https://www.catalogueoflife.org/" target=_blank>COL</a>)'
    end
  end

  def external_homonyms
    # Try IRMNG, which is the fastest and best formatted option
    return irmng_homonyms unless irmng_homonyms.empty?

    # Next, try ITIS, which is slower but very conveniently formatted
    return itis_homonyms unless itis_homonyms.empty?

    # Next, try GBIF, which is fast and well formatted, but includes many
    # questionable sources
    return gbif_homonyms unless gbif_homonyms.empty?

    # Finally, try COL, which is the least convenient but most comprehensive
    ### Excluding COL for now, since it generates too many false positives
    ### that cannot be filtered due to the lack of additional information
    ### return col_homonyms unless col_homonyms.empty?

    []
  end

end

app/models/name/wiki.rb
module Name::Wiki
  def name_wiki(opts = {})
    y = base_name
    if opts[:link] && opts[:eol] && validated? && rank == 'genus'
      return "{{gbr|#{y}}}"
    end

    y = "[[#{y}]]" if opts[:link]
    y = "''Candidatus'' #{y}" if !opts[:no_candidatus] && candidatus?
    return "\"#{y}\"" unless validated?

    y = "''#{y}''"
    if rank == 'species' && parent&.nomenclatural_type_id&.==(id)
      y += " (T#{'s' unless icnp? || icn?})"
    end
    opts[:eol] ? "#{y} <br/>" : y
  end

  def formal_wiki
    y = name_wiki
    y += ' corrig.' if corrigendum_from?
    if not_validly_proposed_in.any?
      y += ' (ex'
      y += not_validly_proposed_in
             .map { |i| " #{sanitize(i.short_citation(:wikispecies))}" }
             .join('; ')
      y += ')'
    end
    if authority || proposed_in
      y += " #{sanitize(authority || proposed_in.short_citation(:wikispecies))}"
    end
    if priority_date && priority_date.year != proposed_in&.journal_date&.year
      y += " (valid #{priority_date.year})"
    end
    if emended_in.any?
      cit = emended_in.map { |p| p.short_citation(:wikispecies) }.join('; ')
      y += " emend. #{cit}"
    end
    sanitize(y.gsub(/{{aut\|/, '{{a|'))
  end

  def wiki_url_name
    base_name.tr(' ', '_')
  end

  def edit_wikispecies_page_link
    'https://species.wikimedia.org/w/index.php?title=%s&action=edit' %
      wiki_url_name
  end

  def edit_wikispecies_template_link
    'https://species.wikimedia.org/w/index.php?title=Template:%s&action=edit' %
      wiki_url_name
  end

  def wikispecies_url
    'https://species.wikimedia.org/wiki/%s' %
      wiki_url_name
  end

  def check_wikispecies
    issues = []
    doc = external_request(wikispecies_url)
    if !doc.present?
      issues << 'missing page'
    else
      xml = Nokogiri::HTML.parse(doc)
      if xml.xpath("//a[@href='#{seqcode_url(true)}']").empty?
        issues << "SeqCode entry not linked"
      end
      if parent && parent.validated? && parent != self
        i = parent.wiki_url_name
        unless xml.xpath("//a[@href='/wiki/#{i}']").any? ||
            xml.xpath("//a[starts-with(@href,'/w/index.php?title=#{i}&')]").any?
          issues << "parent not linked: #{parent.name}"
        end
      end
      valid_children.each do |child|
        i = child.wiki_url_name
        unless xml.xpath("//a[@href='/wiki/#{i}']").any? ||
            xml.xpath("//a[starts-with(@href,'/w/index.php?title=#{i}&')]").any?
          issues <<
            "child not linked: #{child.name}#{' (SeqCode)' if child.seqcode?}"
        end
      end
    end
    update_columns(
      wikispecies_checked_at: DateTime.now,
      wikispecies_issues_text: issues.empty? ? nil : issues.join('; ')
    )
  end

  def wikispecies_issues
    unless wikispecies_checked_at && wikispecies_checked_at > 1.month.ago
      check_wikispecies
    end

    @wikispecies_issues ||= (wikispecies_issues_text || '').split('; ')
  end
end

app/helpers/names_helper.rb
module NamesHelper
  def link_to_name_type(name)
    if name.type_is_name?
      if name.type_name
        display_link(name.type_name, :name_html_correctness) +
        if rep = name.type_name_alt_placement
          content_tag(:span, ' (alternatively placed in ') +
            display_link(rep) +
            content_tag(:span, ')')
        elsif rep = name.type_name.correct_name
          content_tag(:span, ' (correct name: ') +
            display_link(rep) +
            content_tag(:span, ')')
        end
      else
        content_tag(
          :span, "Illegal name: #{name.nomenclatural_type_id}",
          class: 'text-danger'
        )
      end
    elsif name.type_genome
      link_to(name.type_genome.text, name.type_genome)
    elsif name.type_link
      # This section is currently not being used, it was meant for direct
      # external links in genomes, but now genomes have dedicated pages
      link_to(name.type_link, target: '_blank') do
        content_tag(:span, name.type_text) +
          fa_icon('external-link-alt', class: 'ml-1')
      end
    elsif name.type_is_strain?
      strain_html(name)
    else
      name.type_text
    end
  end

  def link_to_name(name)
    link_to(name.name_html, name)
  end

  def name_lineage(name, links: true, last: true, register: nil, visited: [])
    assume_valid = register&.names&.include?(name)
    out = []
    visited << name

    # Recursively get the parent(s)
    if name.incertae_sedis?
      out << content_tag(:span, name.incertae_sedis_html)
      out << content_tag(:span, ' &raquo; '.html_safe)
    elsif name.parent
      if visited.include? name.parent
        out << content_tag(:span, 'Recursion found: ' , class: 'text-danger')
      else
        out << name_lineage(
          name.parent,
          links: links, last: false, register: register, visited: visited
        )
        out << content_tag(:span, ' &raquo; '.html_safe)
      end
    end

    # Display the current name
    if links && !last
      out << display_link(
        name, :name_html,
        display_text: name.name_html(assume_valid: assume_valid)
      )
    else
      out << name.name_html(assume_valid: assume_valid)
    end

    out.inject(:+)
  end
end

app/views/names/_admin.html.erb
<% if current_admin? && @name.validated? %>
  <dl name="admin" class="main-section name-details actions-section">
    <h2>Admin Actions</h2>
    <dd class="pt-2">
      <% if @name.validated? %>
        <%= link_to(
              temporary_editable_name_url(@name),
              method: :post, class: 'btn btn-primary btn-sm',
              data: {
                confirm: 'Are you sure? This can have unintended consequences'
              }
            ) do %>
          <%= fa_icon('stopwatch') %> Temporary editable name
        <% end %>
        &raquo; Make name editable by curators for 10 minutes
        <hr/>
        <%= link_to(
              demote_name_url(@name),
              method: :post, class: 'btn btn-danger btn-sm',
              data: {
                confirm: 'Are you sure? This can have unintended consequences'
              }
            ) do %>
          <%= fa_icon('frown-open') %> Demote name
        <% end %>
        &raquo; Send name back to the status of automated discovery
        <hr/>
      <% end %>
    </dd>
  </dl>
<% end %>

app/views/names/_correspondence.html.erb
<%=
  render(
    partial: 'correspondences/correspondence',
    locals: {
      object: @name, tutorial: tutorial ||= nil
    }
  )
%>

app/views/names/_curator.html.erb
<% if current_curator? %>
  <dl name="curator" class="main-section name-details actions-section">
    <h2>Curator Actions</h2>
    <dd class="pt-2">
      <% if @name.validated? %>
        <%= link_to(
              edit_links_name_url(@name),
              class: 'btn btn-primary btn-sm'
            ) do %>
          <%= fa_icon('edit') %> Edit outside links
        <% end %>
        &raquo; Report links to external databases (other than type)
        <hr/>
      <% else %>
        <% if @name.can_unclaim?(current_user) %>
          <%= link_to(
                unclaim_name_url(@name),
                method: :post, class: 'btn btn-primary btn-sm'
              ) do %>
            <%= fa_icon('user-slash') %> Unclaim name
          <% end %>
          &raquo; Remove ownership of this name and make it public
          <hr/>

          <%= link_to(
                transfer_user_name_url(@name),
                class: 'btn btn-primary btn-sm'
              ) do %>
            <%= fa_icon('people-arrows') %> Transfer to another user
          <% end %>
          &raquo; Transfer the name ownership to a different contributor and
          notify the current owner
          <hr/>
        <% end %>

        <% unless @name.after_endorsement? || !@name.register %>
          <% id = modal('Are you sure?') do %>
            <h5>Endorse individual name</h5>
            <p>
              Please consider that endorsing an individual name can cause
              confusion to authors. To track curation progress in each name,
              consider using the <b>Expert Curation</b> checks instead.
            </p>
            <%= link_to(
                  endorse_name_url(@name),
                  method: :post, class: 'btn btn-primary'
                ) do %>
              <%= fa_icon('check-square') %> Endorse name
            <% end %>
            <%= link_to(@name.register, class: 'btn btn-secondary') do %>
              <%= fa_icon('clipboard-list') %> Visit Register List
            <% end %>
          <% end %>
          <%= modal_button(id, class: 'btn btn-primary btn-sm') do %>
            <%= fa_icon('check-square') %> Endorse name
          <% end %>
          &raquo; Recommend this name as a candidate for validation
          <hr/>
        <% end %>
        <% id = modal('Select code of nomenclature') do %>
          <h5>Validly published under a different code</h5>
          <p>
            Has this name already been validly published under a code of
            nomenclature other than the SeqCode?
            You could also
            <%= link_to('search this name in LPSN',
                        'https://lpsn.dsmz.de/search?word=%s' % @name.name,
                        target: '_blank') %>.
          </p>
          <hr/>
          <h5 class="text-primary">Report valid under</h5>
          <%= link_to(
                validate_name_url(@name, code: :icnp),
                method: :post,
                class: 'btn btn-primary',
                data: { confirm: 'Are you sure? This action cannot be undone' }
              ) do %>
            <%= fa_icon('stamp') %> ICNP
          <% end %>
          <%= link_to(
                validate_name_url(@name, code: :icn),
                method: :post,
                class: 'btn btn-primary',
                data: { confirm: 'Are you sure? This action cannot be undone' }
              ) do %>
            <%= fa_icon('stamp') %> ICNafp (Botanical Code)
          <% end %>
        <% end %>
        <%= modal_button(id, class: 'btn btn-primary btn-sm') do %>
          <%= fa_icon('stamp') %> Report valid under other code
        <% end %>
        &raquo; Indicate that this name has been validly published under another
        code of nomenclature
        <hr/>
        <!-- This option is hidden as register-level actions are to be preferred
        <% if @name.after_submission? %>
          <%= link_to(
                return_name_url(@name),
                method: :post,
                class: 'btn btn-primary btn-sm',
                data: {
                  confirm: 'Are you sure? The author will regain edit access'
                }
              ) do %>
            <%= fa_icon('undo-alt') %> Return to submitter
          <% end %>
          &raquo; Send this name back to the author for additional revisions
          <hr/>
        <% end %>
        -->
      <% end %>
      <%= link_to(
            network_name_url(@name), class: 'btn btn-primary btn-sm'
          ) do %>
        <%= fa_icon('project-diagram') %> Taxonomic network
      <% end %>
      &raquo; Explore the taxonomic network representation of the current name
      <hr/>
      <%= link_to(
            wiki_name_url(@name), class: 'btn btn-primary btn-sm'
          ) do %>
        <%= fa_icon('code') %> Wiki pages
      <% end %>
      &raquo; Generate source for Wikipedia affiliated pages
      <hr/>
      <%= link_to(edit_redirect_name_url(@name),
            class: 'btn btn-sm btn-danger') do %>
        <%= fa_icon('directions') %> Create redirection
      <% end %>
      &raquo; Soft-remove this name and redirect to a different entry
      <hr/>
    </dd>
  </dl>
<% end %>

app/views/names/_genomics.html.erb
<% @genome = @name.genome %>
<%= render(partial: 'genomes/genome') %>

app/views/names/_tutorial.html.erb
<% if @name.tutorial && current_user?(@name.tutorial.user) &&
      @name.tutorial.ongoing? %>
  <div class="alert alert-info">
    You have an ongoing guided registration including this name:
    <b><%= @name.tutorial.title %></b>
    <hr/>
    <%= link_to('Continue', @name.tutorial, class: 'btn btn-info') %>
  </div>
<% end %>

app/views/names/edit_rank.html.erb
<h1>Rank of <%= @name.name_html %></h1>
<hr/>

<% @name.rank ||= @name.inferred_rank %>
<%= simple_form_for(@name) do |f| %>
  <%= f.input(:rank, collection: Name.ranks) %>
  <br/>

  <% if @tutorial %>
    <%= hidden_field_tag(:return_to, tutorial_path(@tutorial, next: true)) %>
  <% end %>
  <%= link_to('Cancel', @tutorial || @name, class: 'btn btn-secondary') %>
  <%= f.button(:submit, 'Submit') %>
  <br/><br/>
<% end %>

app/views/names/edit_redirect.html.erb
<h1>Soft-remove <%= @name.name_html %></h1>
<hr/>

<div class="alert alert-warning">
  This will cause the page's name to redirect to a different entry,
  but the data and metadata might still be accessible.
</div>

<%= simple_form_for(@name) do |f| %>
  <%= hidden_field_tag(:edit, :redirect) %>
  <%=
    f.input(
      :redirect, label: 'Redirect to name',
      input_html: {
        value: @name.redirect&.name,
        data: { behavior: 'autocomplete', autocomplete: 'names' }
      }
    )
  %>
  <%= f.submit('Soft-remove', class: 'btn btn-danger') %>
  <%= link_to('Cancel', @name, class: 'btn btn-secondary') %>
<% end %>

app/views/names/hidden.html.erb
<% provide(:title, @name.abbr_name_raw) %>
<h1><%= @name.name_html %></h1>
<hr/>
<div class="alert alert-warning">
  <h3>Insufficient permits</h3>
  <hr/>
  You don't have access to view this name's details.
  <% if user_signed_in? %>
    If you think this is a mistake, please
    <%= link_to('contact us', page_connect_url) %> to request a change in
    ownership
  <% else %>
    Please <%= link_to('sign in', new_user_session_path) %> and try again to
    check your user's privileges
  <% end %>
</div>
<br/>
<%= render(partial: 'shared/cc') %>

app/views/names/new.html.erb
<br/>
<h1>New Name</h1>
<p class='lead'>
  Carefully revise the spelling of the name before submitting.<br/>
  <%= help_message('What is a name?', text: 'What is a name ') do %>
    <p>
      For the purposes of the SeqCode, a name can be defined as: The label
      applied to an object. A word or set of words by which a taxon is known,
      addressed, or referred to. A term used for identification.
      <br/><br/>
      Provide the novel name proposed for registration and validation under the
      SeqCode.
      If this is a species name, be sure to provide both the genus name and
      species epithet here (<i>e.g.</i>, <i>Wolframiiraptor gerlachensis</i>).
      Upon completion of the information for the species, continue to complete
      the information for registration of the genus
      (<i>e.g.</i>, <i>Wolframiiraptor</i>) and higher taxonomic ranks
      (<i>i.e.</i>, family, order, class, or phylum).
    </p>
  <% end %>
</p>

<%= simple_form_for(@name, html: { method: :post }) do |f| %>
  <%= f.input :name, required: true, autofocus: true %>
  <%= f.button :submit, 'Register' %>
<% end %>

<br/>
<hr/>
<h2>Do you need some inspiration?</h2>
<ul class="mb-5">
  <%
    fa_hash = {
      style: 'min-width: 2em;',
      class: 'text-center border-right border-dark mr-2 pr-2'
    }
  %>
  <li>
    <%= fa_icon('drafting-compass', fa_hash) %>
    <%= link_to(etymology_sandbox_names_url) do %>
      Try-out some ideas in the etymology sandbox
    <% end %>
  </li>
  <li>
    <%= fa_icon('question-circle', fa_hash) %>
    <%= link_to(help_url(:etymology)) do %>
      Read our etymology guide and explore additional resources
    <% end %>
  </li>
  <li>
    <%= fa_icon('compass', fa_hash) %>
    <%= link_to(names_url(status: :SeqCode)) do %>
      Explore names that have already been validly published under the SeqCode
    <% end %>
  </li>
  <li>
    <%= fa_icon('robot', fa_hash) %>
    Explore automated name generation tools like
    <%= link_to('https://github.com/telatin/gan', target: '_blank') do %>
      GAN <%= fa_icon('external-link-alt') %>
    <% end %> and
    <%= link_to('https://github.com/quadram-institute-bioscience/namingGTDB',
            target: '_blank') do %>
      namingGTDB <%= fa_icon('external-link-alt') %>
    <% end %>
  </li>
</ul>

<%= render(partial: 'shared/cc') %>