config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :tags
  # General configuration
  root(to: 'application#main')
  concern(:autocompletable) do
    get  :autocomplete, on: :collection
  end

  # Static pages
  namespace :page do
    %i[
      api about committee connect help initiative issues join
      news prize publications seqcode linkout status
      sandbox stats videos
    ].each { |i| get(i) }
  end
  get  'help' => 'page#help_index', as: :help_index
  get  'help/:topic' => 'page#help', as: :help

  # Users
  get  'sysusers(.:format)' => 'users#index', as: :users
  get  'sysusers/:username(.:format)' => 'users#show', as: :user
  post 'sysusers/:username(.:format)' => 'users#update'
  get  'dashboard' => 'users#dashboard', as: :dashboard
  get  'contributors' => 'users#contributor_request', as: :contributor_request
  post 'contributors' => 'users#contributor_apply', as: :contributor_apply
  post 'contributors/grant/:username' => 'users#contributor_grant', as: :contributor_grant
  post 'contributors/deny/:username' => 'users#contributor_deny', as: :contributor_deny
  get  'curators' => 'users#curator_request', as: :curator_request
  post 'curators' => 'users#curator_apply', as: :curator_apply
  post 'curators/grant/:username' => 'users#curator_grant', as: :curator_grant
  post 'curators/deny/:username' => 'users#curator_deny', as: :curator_deny
  devise_for(:users, controllers: { registrations: 'users/registrations' })

  # Alerts (Notifications)
  resources(
    :notifications, path: 'alerts',
    only: %i[index show update destroy]
  ) do
    collection do
      post :all_seen
      post :all_destroy
    end
    member do
      post :toggle_seen
    end
  end

  # Names
  # --> Index
  get  'type-genomes(.:format)' => 'names#type_genomes', as: :name_type_genomes
  # --> Standard resources
  resources(:names) do
    collection do
      # --> Index
      get  :submitted
      get  :endorsed
      get  :draft
      get  :user
      get  :observing
      get  :linkout
      # --> User utilities
      get  :autocomplete
      get  :etymology_sandbox
      get  :syllabify
      # --> Curator utilities
      get  :unranked
      get  :unknown_proposal
    end
    member do
      # --> Display name
      get  :network
      get  :linkout
      get  :wiki
      # --> Edit name
      get  :edit_description
      get  :edit_type
      get  :edit_etymology
      get  :autofill_etymology
      get  :edit_notes
      get  :edit_rank
      get  :edit_links
      get  :edit_redirect
      post :return
      post :validate
      post :endorse
      post :temporary_editable
      # --> Edit user relationship to name
      get  :observe
      get  :unobserve
      post :claim
      post :unclaim
      post :demote
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Edit name relationships
      get  :edit_parent
      post :new_correspondence
      post :proposed_in, path: '/proposed_in/:publication_id'
      get  :corrigendum_in
      post :corrigendum
      post :emended_in, path: '/emended_in/:publication_id'
      post :assigned_in, path: '/assigned_in/:publication_id'
      post :not_validly_proposed_in,
           path: '/not_validly_proposed_in/:publication_id'
    end
    resources :pseudonyms
  end

  # Taxonomic placements
  resources(:placements, only: %i[create edit update destroy]) do
    post :prefer, on: :member
  end
  get '/placements/new/:name_id', controller: :placements, action: :new, as: :new_placement

  # Genomes
  resources(:genomes) do
    member do
      post  :update_external
      post  :recalculate_miga
      patch :update_accession
      get   :sample_map
    end
  end

  # Strains
  resources(:strains, only: %i[index show]) do
    member do
      get  :strain_info
      get  :link_genome
      post :link_genome_commit
      post :unlink_genome
    end
  end

  # Checks
  post 'check/:name_id(.:format)' => 'checks#update', as: :check

  # Register lists
  # --> Standard resources
  resources(:registers, param: :accession) do
    collection do
      get  :map
    end
    member do
      # --> Display
      get  :table
      get  :list
      get  :cite
      get  :certificate_image
      get  :sample_map
      get  :tree
      get  :reviewer_token
      post :reviewer_token, action: :reviewer_token_create
      delete :reviewer_token, action: :reviewer_token_delete
      # --> Register edit
      post :submit
      get  :return
      post :return, action: :return_commit
      post :endorse
      get  :notify
      post :notify, action: :notify_commit
      get  :prenotify
      post :prenotify, action: :prenotify_commit
      post :validate
      get  :editorial_checks
      get  :publish
      post :publish, action: :publish_commit
      patch :internal_notes
      post :nomenclature_review
      post :genomics_review
      get  :merge
      post :merge, action: :merge_commit
      get  :coauthors
      post :coauthors, action: :coauthors_commit
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Special curation pages
      get  :curation_genomics
      post :snooze_curation
      post :recheck_pdf_files
      # --> Edit user relationship to register list
      get  :observe
      get  :unobserve
      # --> Edit register relationships
      post :new_correspondence
    end
  end

  # Authors
  resources(:authors, concerns: :autocompletable)

  # Journals
  resources(:journals, only: %i[index show], param: :journal)

  # Publications
  resources(:publications, concerns: :autocompletable) do
    resources(:contacts, only: %i[new create show index])
    member do
      get  :names
    end
  end
  get  'doi/:doi' => 'publications#show', as: :doi, doi: /.+/
  resources(:contacts, only: []) do
    collection do
      get  :user
    end
  end

  # Publication Names (n:m relationship)
  get  'publications/:id/link_name' => 'publication_names#link_name', as: :link_publication_name
  post 'publications/:id/link_name' => 'publication_names#link_name_commit', as: :link_publication_commit_name

  # Other resources
  resources(:subjects, concerns: :autocompletable)
  resources(:tutorials, :publication_names)
  resources(:correspondences, only: []) do
    collection do
      get  :template
    end
  end
  resources(:curations, only: %i[create update])

  # Reports
  get 'reports/genomes/:id', to: 'reports#genome', as: :reports_genome

  # General Application
  get  'link' => 'application#short_link'
  get  'link/:path(.:format)' => 'application#short_link'
  get  'set/list' => 'application#set_list', as: :set_list
  get  'search' => 'application#search', as: :search
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action(
    :set_publication,
    only: %i[show edit update destroy names]
  )
  before_action(
    :authenticate_contributor!, only: %i[new edit create update destroy]
  )

  # GET /publications
  # GET /publications.json
  def index
    @sort = params[:sort]
    @publications =
      case @sort
      when 'names'
        Publication
          .left_joins(:publication_names).group(:id)
          .reorder('COUNT(publication_names.id) DESC')
      else
        @sort = 'date'
        Publication
      end
    @publications = @publications.paginate(page: params[:page], per_page: 10)

    @count = @publications.count
    @count = @count.size if @count.is_a? Hash
    @crumbs = ['Publications']
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @crumbs = [['Publications', publications_path], @publication.short_citation]
  end

  # GET /publications/1/names
  def names
    render(layout: !params[:content].present?)
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    @name = Name.find(params[:link_name]) if params[:link_name]
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  def create
    @publication = Publication.by_doi(params['publication']['doi'])
    if @publication.new_record?
      render('new')
    else
      if params[:link_name] && params[:link_name][:id]
        @name = Name.find(params[:link_name][:id])
        par = { publication: @publication, name: @name }
        pn = PublicationName.find_or_create_by(par)

        case params[:link_name][:as]
        when 'propose'
          @name.update(proposed_in: @publication)
          flash[:notice] = 'Effective publication registered'
        when 'not_valid_proposal'
          pn.update(not_valid_proposal: true)
          flash[:notice] =
            'Original (not valid) publication registered'
        when 'corrig'
          redirect_to(
            corrigendum_in_name_url(@name, publication_id: @publication.id)
          )
          return
        when 'assign'
          @name.update(assigned_in: @publication)
          flash[:notice] = 'Taxonomic assignment publication registered'
        when 'emend'
          pn.update(emends: true)
          flash[:notice] = 'Emending publication registered'
        else
          flash[:notice] = 'Publication registered'
        end
        redirect_to(@name)
      else
        redirect_to(@publication)
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /publications/autocomplete.json?q=List
  def autocomplete
    publication = params[:q].downcase
    @publications =
      Publication.where('LOWER(title) LIKE ?', "%#{publication}%")
          .or(Publication.where('LOWER(doi) LIKE ?', publication))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = params[:id] ? Publication.find(params[:id]) :
        params[:doi] ? Publication.find_by(doi: params[:doi]) : nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication)
        .permit(*%i[
          title journal journal_loc journal_date doi url pub_type
          crossref_json abstract
        ])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
  def publication_full_citation(publication)
    content_tag(:span, publication.authors_et_al_html) +
    content_tag(:span, ' (%i). ' % publication.journal_date.year) +
    if publication.journal.empty?
      content_tag(:span, publication.journal_html, class: 'text-muted')
    else
      content_tag(:em) do
        link_to(publication.journal, journal_path(publication.journal))
      end + ' ' +
      publication.journal_loc
    end
  end
end

app/views/publications/_basic_info.html.erb
<dt><%= fa_icon('book-open') %> Citation</dt>
<dd><%= publication_full_citation(publication) %></dd>

<% if current_contributor? || !publication.names.empty? %>
  <dt>
    <%= fa_icon('list-ul') %> Names
    <span class="text-muted">(<%= publication.names.count %>)</span>
  </dt>
  <dd>
    <% publication.publication_names.each do |publication_name| %>
      <% name = publication_name.name %>
      <div class="btn-group badge-pill-group" role="group">
        <%= link_to(
              name.abbr_name, name, class: 'badge badge-pill badge-primary') %>
        <% if current_contributor? %>
          <%= link_to(
                publication_name, method: :delete,
                class: 'badge badge-pill badge-info px-2', title: 'unlink name',
                data: { confirm: 'Are you sure?' }
              ) { %><%= fa_icon('unlink') %><% } %>
        <% end %>
      </div>
    <% end %>
    <% if current_contributor? %>
      <%= link_to(
            link_publication_name_path(publication),
            class: 'badge badge-pill badge-info', title: 'link names'
          ) { %><%= fa_icon('plus') %> <%= fa_icon('link') %><% } %>
    <% end %>
  </dd>
<% end %>

<% unless publication.subjects.empty? %>
  <dt><%= fa_icon('tags') %> Subjects</dt>
  <dd>
  <% publication.subjects.each do |subject| %>
    <%= link_to(
          subject.name, subject,
          class: 'badge badge-pill badge-secondary'
        ) %>
  <% end %>
  </dd>
<% end %>

<% if publication.abstract %>
  <dt><%= fa_icon('file-alt') %> Abstract</dt>
  <dd class='text-sm text-muted'><%= publication.clean_abstract %></dd>
<% end %>

app/views/publications/_curator.html.erb
<% if current_curator? %>
  <dl name="curator" class="main-section name-details actions-section">
    <h2>Curator Actions</h2>
    <dd class="pt-2">
      <%= link_to(
            new_publication_contact_url(@publication),
            class: 'btn btn-primary btn-sm'
          ) do %>
        <%= fa_icon('envelope') %> Contact authors
      <% end %>
      &raquo; Send message to authors related to the current publication
    </dd>
  </dl>
<% end %>

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, 'error') %>
          prohibited this publication from being saved:</h2>
      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :publication_title %>
  </div>

  <div class="field">
    <%= form.label :journal %>
    <%= form.text_field :journal, id: :publication_journal %>
  </div>

  <div class="field">
    <%= form.label :journal_loc %>
    <%= form.text_field :journal_loc, id: :publication_journal_loc %>
  </div>

  <div class="field">
    <%= form.label :journal_date %>
    <%= form.date_select :journal_date, id: :publication_journal_date %>
  </div>

  <div class="field">
    <%= form.label :doi %>
    <%= form.text_field :doi, id: :publication_doi %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :publication_url %>
  </div>

  <div class="field">
    <%= form.label :pub_type %>
    <%= form.text_field :pub_type, id: :publication_pub_type %>
  </div>

  <div class="field">
    <%= form.label :crossref_json %>
    <%= form.text_field :crossref_json, id: :publication_crossref_json %>
  </div>

  <div class="field">
    <%= form.label :abstract %>
    <%= form.text_field :abstract, id: :publication_abstract %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_names.html.erb
<% publication.publication_names.each do |publication_name| %>
  <% name = publication_name.name %>
  <%= link_to(
        name.abbr_name, name, class: 'badge badge-pill badge-primary') %>
  <% if current_contributor? %>
    <%= link_to(
          publication_name, method: :delete,
          class: 'badge badge-pill badge-info', title: 'unlink name',
          data: { confirm: 'Are you sure?' }
        ) { %><%= fa_icon('trash-alt') %><% } %>
  <% end %>
<% end %>
<% if current_contributor? %>
  <%= link_to(
        link_publication_name_path(publication),
        class: 'badge badge-pill badge-info', title: 'link names'
      ) { %><%= fa_icon('link') %><% } %>
<% end %>

app/views/publications/_publication.html.erb
<%= adaptable_entry(list, publication.title_html, publication) do |entry| %>
  <%= adaptable_value(entry, 'Citation') do %>
    <%= publication_full_citation(publication) %>
  <% end %>

  <%= adaptable_value(entry, 'Names') do %>
    <% if publication.names.count > 10 %>
      <% id = modal(
            'Publication names',
            async: names_publication_url(publication, content: true),
            size: 'xl'
          ) { %> Loading names... <% } %>
       <%= modal_button(id, class: 'badge badge-secondary') do %>
         <%= fa_icon('ellipsis-h') %>
         <%= pluralize(publication.names.count, 'Name') %>
       <% end %>
    <% else %>
      <%= render(
            partial: 'publications/names',
            locals: { publication: publication }) %>
    <% end %>
  <% end %>

  <%= adaptable_value(entry, 'Abstract') do %>
    <% len = entry.list.type == :table ? 0 : 500 %>
    <% if publication.abstract? %>
      <div class='text-sm text-muted'>
        <%= publication.clean_abstract[0, len] %>
      </div>
      <% if publication.clean_abstract.length > len %>
        <% id = modal(publication.title_html, size: 'lg') do %>
          <%= publication.clean_abstract %>
        <% end %>
        <%= modal_button(id, class: 'badge-secondary badge') do %>
          <%= fa_icon('ellipsis-h') %> Text
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <% entry.footer do %>
    <ul class="list-inline m-0 text-right">
      <li class="list-inline-item m-0">
        <%= link_to(
              publication.url,
              title: 'Link to publication', target: '_blank'
            ) { %><%= fa_icon('file-alt') %><% } %>
      </li>
      <li class="list-inline-item m-0">
        <%= link_to(publication, title: 'See more') do %>
          <%= fa_icon('arrow-circle-right') %>
        <% end %>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<%
  npar = {}
  npar[:sort]   = @sort if @sort.present?
  ppar = { page: params[:page] || 1 }.merge(npar)
%>
<% provide(:canonical_url, canonical_url(ppar)) %>
<%= download_buttons(
      [[publications_url(ppar.merge(format: :json)), 'file-code', 'JSON']]
    ) %>

<h1>
  Publications
  <div class="badge badge-count"><%= @count %></div>
</h1>

<div class="container p-0">
  <div class="row">
    <div class="col-sm-9">
      <b>Sort by</b>
      <% %w[date names].map do |sort| %>
        <span class="text-muted">•</span>
        <%= sort == @sort ?
              sort : link_to(sort, publications_path(sort: sort)) %>
      <% end %>
      <br/>
      <b>Browse by</b>
      <% %i[authors subjects journals].each do |what| %>
        <span class="text-muted">•</span>
        <%= link_to(what, what) %>
      <% end %>
    </div>
    <div class="col-sm-3 text-right">
      <% if current_contributor? %>
        <%= link_to(new_publication_path) do %>
          Register publication
          <%= fa_icon('plus-circle') %>
        <% end %>
      <% end %>
      <br/>
      <%= list_type_selector %>
    </div>
  </div>
</div>
<hr/>

<%= adaptable_list(set: @publications) do |list| %>
  <% @publications.each do |i| %>
    <%= render(partial: i, locals: { list: list }) %>
  <% end %>
<% end %>

app/views/publications/names.html.erb
<%= render(partial: 'names', locals: { publication: @publication }) %>

app/views/publications/new.html.erb
<br/>
<h1>New Publication</h1>
<p class="lead">
  Only publications with assigned Digital Object Identifier
  (<%= link_to('DOI', 'https://doi.org/', target: '_blank') %>)
  can be registered
</p>

<%= simple_form_for(@publication, hrml: { method: :post }) do |f| %>
  <%= f.input(:doi,
              required: true, autofocus: true, label: 'DOI of publication') %>
  <% if @name %>
    <%= hidden_field(:link_name, :id, value: @name.id) %>
    <p>
      This publication will be automatically linked to
      <%= link_to(@name) { @name.abbr_name } %>:
      <div class="m-3">
        <label>
          <%= radio_button(:link_name, :as, :propose) %>
          Proposing the name (effective publication)
          <%= help_message('Effective Publication') do %>
            For the purposes of the SeqCode, an <b>effective publication</b>
            refers to the peer-reviewed publication in which a name and evidence
            for the taxon first appears. Under the SeqCode, preprints are not
            eligible as an effective publication.<br/><br/>
            See <%= link_to_rule('24a', 'Rule 24') %> for additional
            explanation.
          <% end %>
        </label><br/>
        <label>
          <%= radio_button(:link_name, :as, :not_valid_proposal) %>
          Original (not valid) publication
          <%= help_message('Not Valid Publication of Proposal') do %>
            This is the original publication proposing the name or the
            establishment of this taxon, but it did not meet all minimum
            criteria for valid publication under the SeqCode. For example, it
            proposed this name on the basis of marker genes or low-quality
            genomes as nomenclatural type, or used a non-validly published
            name as type.
          <% end %>
        </label><br/>
        <label>
          <%= radio_button(:link_name, :as, :emend) %>
          Emending the name (<i>emend.</i>)
        </label><br/>
        <label>
          <%= radio_button(:link_name, :as, :corrig) %>
          Correcting the name (<i>corrig.</i>)
        </label><br/>
        <label>
          <%= radio_button(:link_name, :as, :cite, checked: true) %>
          Citing the name
        </label>
      </div>
    </p>
    <%= link_to('Cancel', @name, class: 'btn btn-secondary') %>
  <% end %>
  <%= f.button(:submit, 'Register') %>
<% end %>

app/views/publications/show.html.erb
<% provide(:title, @publication.title) %>
<% provide(:canonical_url, canonical_url) %>
<%= download_buttons(
      [[publication_url(@publication, format: :json), 'file-code', 'JSON']]) %>
<h1><%= @publication.title_html %></h1>
<hr/>

<dl class="main-section name-details">
  <h2>
    <%= fa_icon('newspaper', class: 'float-right') %>
    Publication
  </h2>
  <%= render partial: 'basic_info', locals: { publication: @publication } %>
  <dt>
    <% n = @publication.publication_authors.size %>
    <%= fa_icon('user-friends') %>
    <%= n == 1 ? 'Author' : 'Authors' %>
  </dt>
  <dd>
    <% @publication.publication_authors.each_with_index do |p_author, k| %>
      <% author = p_author.author %>
      <%= link_to author.full_name, author %><%= '; ' if k < n - 1 %>
    <% end %>
  </dd>
  <dt><%= fa_icon('calendar-day') %> Publication date</dt>
  <dd><%= @publication.journal_date %></dd>
  <dt><%= fa_icon('directions') %> DOI</dt>
  <dd>
    <%= link_to(@publication.url, target: '_blank') do %>
      <%= @publication.doi %>&nbsp;
      <%= fa_icon('external-link-alt') %>
    <% end %>
  </dd>
</dl>
<%= render(partial: 'curator') %>
<br/>
<%= render(partial: 'shared/cc') %>