config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :tags
  # General configuration
  root(to: 'application#main')
  concern(:autocompletable) do
    get  :autocomplete, on: :collection
  end

  # Static pages
  namespace :page do
    %i[
      api about committee connect help initiative issues join
      news prize publications seqcode linkout status
      sandbox stats videos
    ].each { |i| get(i) }
  end
  get  'help' => 'page#help_index', as: :help_index
  get  'help/:topic' => 'page#help', as: :help

  # Users
  get  'sysusers(.:format)' => 'users#index', as: :users
  get  'sysusers/:username(.:format)' => 'users#show', as: :user
  post 'sysusers/:username(.:format)' => 'users#update'
  get  'dashboard' => 'users#dashboard', as: :dashboard
  get  'contributors' => 'users#contributor_request', as: :contributor_request
  post 'contributors' => 'users#contributor_apply', as: :contributor_apply
  post 'contributors/grant/:username' => 'users#contributor_grant', as: :contributor_grant
  post 'contributors/deny/:username' => 'users#contributor_deny', as: :contributor_deny
  get  'curators' => 'users#curator_request', as: :curator_request
  post 'curators' => 'users#curator_apply', as: :curator_apply
  post 'curators/grant/:username' => 'users#curator_grant', as: :curator_grant
  post 'curators/deny/:username' => 'users#curator_deny', as: :curator_deny
  devise_for(:users, controllers: { registrations: 'users/registrations' })

  # Alerts (Notifications)
  resources(
    :notifications, path: 'alerts',
    only: %i[index show update destroy]
  ) do
    collection do
      post :all_seen
      post :all_destroy
    end
    member do
      post :toggle_seen
    end
  end

  # Names
  # --> Index
  get  'type-genomes(.:format)' => 'names#type_genomes', as: :name_type_genomes
  # --> Standard resources
  resources(:names) do
    collection do
      # --> Index
      get  :submitted
      get  :endorsed
      get  :draft
      get  :user
      get  :observing
      get  :linkout
      # --> User utilities
      get  :autocomplete
      get  :etymology_sandbox
      get  :syllabify
      # --> Curator utilities
      get  :unranked
      get  :unknown_proposal
    end
    member do
      # --> Display name
      get  :network
      get  :linkout
      get  :wiki
      # --> Edit name
      get  :edit_description
      get  :edit_type
      get  :edit_etymology
      get  :autofill_etymology
      get  :edit_notes
      get  :edit_rank
      get  :edit_links
      get  :edit_redirect
      post :return
      post :validate
      post :endorse
      post :temporary_editable
      # --> Edit user relationship to name
      get  :observe
      get  :unobserve
      post :claim
      post :unclaim
      post :demote
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Edit name relationships
      get  :edit_parent
      post :new_correspondence
      post :proposed_in, path: '/proposed_in/:publication_id'
      get  :corrigendum_in
      post :corrigendum
      post :emended_in, path: '/emended_in/:publication_id'
      post :assigned_in, path: '/assigned_in/:publication_id'
      post :not_validly_proposed_in,
           path: '/not_validly_proposed_in/:publication_id'
    end
    resources :pseudonyms
  end

  # Taxonomic placements
  resources(:placements, only: %i[create edit update destroy]) do
    post :prefer, on: :member
  end
  get '/placements/new/:name_id', controller: :placements, action: :new, as: :new_placement

  # Genomes
  resources(:genomes) do
    member do
      post  :update_external
      post  :recalculate_miga
      patch :update_accession
      get   :sample_map
    end
  end

  # Strains
  resources(:strains, only: %i[index show]) do
    member do
      get  :strain_info
      get  :link_genome
      post :link_genome_commit
      post :unlink_genome
    end
  end

  # Checks
  post 'check/:name_id(.:format)' => 'checks#update', as: :check

  # Register lists
  # --> Standard resources
  resources(:registers, param: :accession) do
    collection do
      get  :map
    end
    member do
      # --> Display
      get  :table
      get  :list
      get  :cite
      get  :certificate_image
      get  :sample_map
      get  :tree
      get  :reviewer_token
      post :reviewer_token, action: :reviewer_token_create
      delete :reviewer_token, action: :reviewer_token_delete
      # --> Register edit
      post :submit
      get  :return
      post :return, action: :return_commit
      post :endorse
      get  :notify
      post :notify, action: :notify_commit
      get  :prenotify
      post :prenotify, action: :prenotify_commit
      post :validate
      get  :editorial_checks
      get  :publish
      post :publish, action: :publish_commit
      patch :internal_notes
      post :nomenclature_review
      post :genomics_review
      get  :merge
      post :merge, action: :merge_commit
      get  :coauthors
      post :coauthors, action: :coauthors_commit
      get  :transfer_user
      post :transfer_user, action: :transfer_user_commit
      # --> Special curation pages
      get  :curation_genomics
      post :snooze_curation
      post :recheck_pdf_files
      # --> Edit user relationship to register list
      get  :observe
      get  :unobserve
      # --> Edit register relationships
      post :new_correspondence
    end
  end

  # Authors
  resources(:authors, concerns: :autocompletable)

  # Journals
  resources(:journals, only: %i[index show], param: :journal)

  # Publications
  resources(:publications, concerns: :autocompletable) do
    resources(:contacts, only: %i[new create show index])
    member do
      get  :names
    end
  end
  get  'doi/:doi' => 'publications#show', as: :doi, doi: /.+/
  resources(:contacts, only: []) do
    collection do
      get  :user
    end
  end

  # Publication Names (n:m relationship)
  get  'publications/:id/link_name' => 'publication_names#link_name', as: :link_publication_name
  post 'publications/:id/link_name' => 'publication_names#link_name_commit', as: :link_publication_commit_name

  # Other resources
  resources(:subjects, concerns: :autocompletable)
  resources(:tutorials, :publication_names)
  resources(:correspondences, only: []) do
    collection do
      get  :template
    end
  end
  resources(:curations, only: %i[create update])

  # Reports
  get 'reports/genomes/:id', to: 'reports#genome', as: :reports_genome

  # General Application
  get  'link' => 'application#short_link'
  get  'link/:path(.:format)' => 'application#short_link'
  get  'set/list' => 'application#set_list', as: :set_list
  get  'search' => 'application#search', as: :search
end

app/views/shared/_cc.html.erb
<div class="alert alert-info text-center">
  <b>&copy; 2022-<%= Date.today.year %> The SeqCode Initiative</b>
  <br/>

  <%= fa_icon('creative-commons', type: :fab) %>
  <%= fa_icon('creative-commons-by', type: :fab) %>
  &nbsp;

  All information contributed to the SeqCode Registry is released under
  the terms of the
  <%= link_to(
        'https://creativecommons.org/licenses/by/4.0/', target: :_blank
      ) do %>
    Creative Commons Attribution (CC BY) 4.0
  <% end %>
  license
</div>

app/views/shared/_correspondence.html.erb
<% if object&.can_view_correspondence?(current_user) ||
      correspondence_history ||= false %>
  <dl id="correspondence" class="main-section name-details">
    <% if correspondence_history %>
      <%= render(
            partial: 'shared/correspondence_history',
            locals: { object: object }) %>
    <% else %>
      <h2>
        <%= fa_icon('comments', class: 'float-right') %>
        Correspondence with curators
      </h2>
      <% if object.correspondences.count > 3 %>
        <% id = modal('Full correspondence history', size: 'lg') do %>
          <%= render(
                partial: 'shared/correspondence_history',
                locals: { object: object }) %>
        <% end %>
        <%= modal_button(id, class: 'my-3 btn btn-secondary') do %>
          <%= pluralize(object.correspondences.count - 3, 'earlier message') %>
          &hellip;
        <% end %>
      <% end %>
      <% object.correspondences.last(3).each do |correspondence| %>
        <%= render(
              partial: 'shared/correspondence_message',
              locals: { correspondence: correspondence }) %>
      <% end %>

      <dt>New message</dt>
      <dd class="pt-2">
        <%
          fpar =
            if object.is_a? Register
              [RegisterCorrespondence.new(notify: true),
                new_correspondence_register_url(accession: object.accession)]
            elsif object.is_a? Name
              par = { id: object.id }
              tutorial ||= nil
              par[:tutorial] = tutorial if tutorial
              [NameCorrespondence.new(notify: true),
                new_correspondence_name_url(par)]
            end
        %>
        <%= simple_form_for(fpar[0], url: fpar[1], method: :post) do |f| %>
          <%= f.input(:message, as: :rich_text_area, label: false) %>
          <%= f.input(:notify, as: :boolean, label_html: { class: 'text-dark' },
                label: 'Notify corresponding users by email') %>
          <%= f.button(:submit, 'Send message') %>
          &raquo; The messages will be in the permanent record,
          visible only to submitter and curators
        <% end %>
      </dd>
    <% end %>
  </dl>
<% end %>

app/views/shared/_correspondence_history.html.erb
<% object.correspondences.each do |correspondence| %>
  <%= render(
        partial: 'shared/correspondence_message',
        locals: { correspondence: correspondence }) %>
<% end %>
<% if object.correspondences.empty? %>
  No messages on record
<% end %>

app/views/shared/_correspondence_message.html.erb
<% automatic =
      correspondence.respond_to?(:automatic) && correspondence.automatic %>
<dt>
  <%= fa_icon(automatic ? 'robot' : 'comment') %>
  <%= link_to(correspondence.user) do %>
    <%= correspondence.user.username %>
    <% if correspondence.user.curator? &&
          !correspondence.obj.user?(correspondence.user) %>
      <span class="badge rounded-pill bg-secondary text-light">
        curator
      </span>
    <% end %>
  <% end %>
  <% if automatic %>
    <span class="text-muted">(automatic message)</span>
  <% end %>
  <span title="<%= correspondence.created_at %>">
    <%= time_ago_in_words(correspondence.created_at) %> ago
  </span>
</dt>
<dd><%= correspondence.message %></dd>

app/views/shared/_search_bar.html.erb
<% autofocus ||= false %>
<%= form_tag(search_path, method: :get, class: '') do %>
  <div class="form-row input-group">
    <div class="input-group-prepend">
      <select class="form-control custom-select btn bg-light"
            name="what" id="search-bar-what">
        <% %w[names genomes publications authors subjects].each do |i| %>
          <option value="<%= i %>" <%= 'selected' if @what.to_s == i %>>
            <%= i.capitalize %>
          </option>
        <% end %>
      </select>
    </div>
    <input type="text" class="form-control bg-light" id="search-bar"
          placeholder="Search" name="q" value="<%= @q %>"
          <%= 'autofocus=autofocus' if autofocus %> />
    <div class="input-group-append">
      <button type="submit" class="btn btn-primary form-control">
        <%= fa_icon('search') %>
      </button>
    </div>
  </div>
<% end %>

<%#
<script>
  $('#search-bar-what').on("change", function() {
    var what = $('#search-bar-what option:selected').val();
    var bar  = $('#search-bar');
    bar.data("autocomplete", what);
  });
</script>
%>

app/views/shared/_user_links.html.erb
<ul class="navbar-nav">
  <li class="nav-item">
    <%= link_to(page_about_path, title: 'About the SeqCode Registry') do %>
      <span class="nav-item-text">About</span>
      <%= fa_icon('question-circle') %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= modal_button(@search_id, class: '', tag: :a) do %>
      <span class="nav-item-text">Search</span>
      <%= fa_icon('search') %>
    <% end %>
  </li>
  <li class="nav-text">
    •
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to(notifications_path, title: 'Alerts') do %>
        <span class="d-lg-none">Notifications</span>
        <span id="notification-count-badge"
          data-count="<%= current_user.unseen_notifications.count %>"
          class="nav-item-text badge badge-pill badge-info py-1 px-2 mr-1"
          ><% if current_user.unseen_notifications.any? %>
            <%= current_user.unseen_notifications.count %>
          <% end %></span>
        <%= fa_icon('bell') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to(dashboard_path, title: 'Dashboard') do %>
        <span class="nav-item-text">Dashboard</span>
        <%= fa_icon('tachometer-alt') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to(
            destroy_user_session_path, method: :delete, title: 'Logout') do %>
        <span class="nav-item-text">Logout</span>
        <%= fa_icon('sign-out-alt') %>
      <% end %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to(new_user_session_path, title: 'Login') do %>
        <span class="nav-item-text">Login</span>
        <%= fa_icon('user-circle') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to(new_user_registration_path, title: 'Register') do %>
        <span class="nav-item-text">Register</span>
        <%= fa_icon('user-plus') %>
      <% end %>
    </li>
  <% end %>
</ul>